### ISSUE TITLE
Visualizing the test result

### ISSUE THREAD

**Issue by priyapaul** [chen1474147/Deep3DPose-1-skel#4]
I have tested an image from the data you have provided in the project website. 

1. How can I visualize the 15 x 3 data in SCAPE or Blender?
2. The ground truth joint- 3D coordinates are defined in Blender's local coordinate system/camera coordinate system or that of SCAPE? This is not clear , also from the paper, how  the  coordinates  can be mapped to real-world.

Thank you

**Comment by chen1474147** [comment]
1, you can draw it in OpenGL
2, in camera coordinate
